[tool.poetry]
name = "apeiron"
version = "0.1.0"
description = "raw pygame is not nice"
authors = ["nwxnk <nwxnk@yandex.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pygame = "^2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"